version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432
  app:
    build: .
    depends_on: 
      - postgres
    env_file:
      - .env